spring.application.name=talentMatch

spring.datasource.url = jdbc:postgresql://localhost:5432/talentMatch
spring.datasource.username = postgres
spring.datasource.password =

spring.jpa.hibernate.ddl-auto=update