spring.application.name=talentMatch

spring.datasource.url = jdbc:postgresql://localhost:5432/talentMatch
spring.datasource.username = postgres
spring.datasource.password = postgres@12

spring.jpa.hibernate.ddl-auto=update

#temp password used for auth
spring.security.user.name=user
spring.security.user.password={noop}user

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavimekhe61@gmail.com
spring.mail.password=gnpq rghw jbai pzsm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
