spring.application.name=talentMatch

spring.datasource.url = jdbc:postgresql://localhost:5432/talentMatch
spring.datasource.username = postgres
spring.datasource.password = postgres@12

spring.jpa.hibernate.ddl-auto=update

#temp password used for auth
spring.security.user.name=user
spring.security.user.password={noop}user

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavimekhe61@gmail.com
spring.mail.password=gnpq rghw jbai pzsm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Producer: Convert JobEvent object to JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer: Convert JSON back to JobEvent object
spring.kafka.consumer.group-id=talent-match-group-v2
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.job.talenMatch.dto